---
inputs:
- type: git
  branch: master
  service: ${PIPELINE_REPO}
  path: .pipeline
triggers:
- type: git
  name: Git PR Trigger
  service: ${PIPELINE_REPO}
  branch: master
  events: '{"push":true,"pull_request":true,"pull_request_closed":false}'
  eventListener: EventListener
- type: manual
  name: Manual Trigger
  eventListener: EventListener
properties:
- name: vault_name
  value: ${VAULT_INSTANCE}
  type: text
- name: validation_signer
  value: ${VALIDATION_SIGNER}
  type: text
- name: prod-region
  value: ${BUILD_REGION_ID}
  type: text
- name: registry-region
  value: ${REGISTRY_REGION_ID}
  type: text
- name: prod-resource-group
  value: ${BUILD_RESOURCE_GROUP}
  type: text
- name: build-cluster-namespace
  value: ${BUILD_CLUSTER_NAMESPACE}
  type: text
- name: app-name
  value: ${APP_NAME}
  type: text
- name: registry-namespace
  value: ${REGISTRY_NAMESPACE}
  type: text
- name: repo
  value: ${PIPELINE_REPO}
  type: text
- name: revision
  value: master
  type: text
- name: prod-cluster-namespace
  value: ${PROD_CLUSTER_NAMESPACE}
  type: text
- name: api-key
  value: ${API_KEY}
  type: SECURE
- name: prod-cluster-name
  value: ${PROD_CLUSTER_NAME}
  type: text
- name: prod-resource-group
  value: ${PROD_RESOURCE_GROUP}
  type: text
- name: prod-cluster-name
  value: ${BUILD_CLUSTER_NAME}
  type: text
- name: build_signer
  value: ${BUILD_SIGNER}
  type: text
- name: prod-region
  value: ${PROD_REGION_ID}
  type: text
